name: couchkeys
description: Customizable virtual keyboard designed for use with D-pads (like Android TV)
version: 1.0.0
repository: https://github.com/arafatamim/couchkeys

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
