name: couchkeys
description: Customizable virtual keyboard for D-pads
version: 0.0.1
repository: https://github.com/arafatamim/couchkeys

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
